name: Reliability and Technical Support
favicon: null
layout_spectrum: 0.50615
typography_spectrum: 1
title: Reliability and Technical Support - MSD
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ebd9c1'
    - '#c69577'
    - '#c9b497'
    - '#583927'
    - '#a35c48'
  brandStrength: 0.6580172886606306
  lightness: 0.052364612463861704
  saturation: 0.10392225021496415
  rhythmicContrast: 0.5541406213305891
purpose: []
